sudo: false
language: php
php:
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"
    - "5.2"
before_script:
  - nvm install node
  - nvm use node
  - node --version
  - npm install
script:
  - gulp deploy